### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by denys-hryshakin** [denys-hryshakin/homepage#5]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by colloborator-bsa** [comment]
>People talk about tactics, but when you look at it, tactics are just players. You change things so that the team can get the most out of the skills they have to offer, but you don't go any further than that. The fundamentals, what I want, which is to take the ball, try to play as offensive as possible and dominate the game through the ball, is the same. I grew up with that; I was a player with that idea, and I am a coach with that idea.
>- Pep Guardiola

**Comment by denys-hryshakin** [comment]
<h2><i>R&Eacute;SUM&Eacute;</h2>
<p><q>People talk about tactics, but when you look at it, tactics are just players. You change things so that the team can get the most out of the skills they have to offer, but you don't go any further than that. The fundamentals, what I want, which is to take the ball, try to play as offensive as possible and dominate the game through the ball, is the same. I grew up with that; I was a player with that idea, and I am a coach with that idea.
</q> &mdash; Pep Guardiola</p>
