### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by denys-hryshakin** [denys-hryshakin/homepage#6]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by colloborator-bsa** [comment]
**PEP GUARDIOLA**

- [Facebook](https://www.facebook.com/PepGuardiolaTeam)
- [Instagram](https://www.instagram.com/pepteam/)
- [Twitter](https://twitter.com/PepTeam)
- [Manchester City](https://www.mancity.com/players/pep-guardiola)
