### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by denys-hryshakin** [denys-hryshakin/homepage#7]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by colloborator-bsa** [comment]
*PLAYER CAREER*
-

**1984**
Started my playing career in 1984 when he joined La Masia at the age of 13. Johan Cruyff instantly saw something special in me.

**1990**
Cruyff gave me first team debut at age of 19 where I made my name playing as a deep-lying playmaker or defensive midfielder in a 2-0 win over Cádiz.

**1991-96**
Became a regular in Cruyff's "Dream Team" at the age of 20 and won 11 trophies like La Liga, the Copa del Rey, the Supercopa de España, and the European Cup Winners' Cup.

**1997**
Was named as Barcelona captain.

**2001-07**
After leaving Barcelona in 2001 at age 30, joined Serie A side Brescia as Andrea Pirlo's replacement in the deep-lying playmaking role.  Following my stint at Brescia, transferred to Roma. After his career with Brescia and Roma, in 2003, Guardiola chose to play in Qatar with Al-Ahli from Doha in the Qatar Stars League. 

*INTERNATIONAL CAREER*
-

**1992**
Guardiola made his senior debut on 14 October in a World Cup qualifier. In the same year, Guardiola captained Spain when they won a gold medal at the Barcelona Olympic Games.

**1994**
Was a member of the Spanish team during the 1994 World Cup, where we reached the quarter-finals

*MANAGERIAL CAREER*
-

**2007**
Started my coaching career the same way I started my player career, at Barcelona. 

**2008–09**
Became a coach of the Barcelona first team and made the historic treble, won everething in the one year. 
Became the youngest man to coach a Champions League winning team.

**2009-10**
Guardiola finished the calendar year 2009 with a record six trophies, the Spanish League, Copa del Rey, Champions League, Spanish Super Cup, European Super Cup and Club World Cup, becoming the first manager in history to do so.
Became the first manager in Barcelona's history to beat Real Madrid four times in a row in El Clásico.

**2010-11**
Won the La Liga title and the club's third in a row after a 1–1 draw with Levante. 
On 28 May, Barcelona beat Manchester United 3–1 at Wembley Stadium to win the Champions League.

**2011-12**
Barcelona won their second trophy of the season.
Won 12 trophies only in three years.
Coached 200 matches with the record 144 wins, 39 draws and 17 losses with 500 goals for and 143 against.

**2013-16**
Became the manager of Champions League winners Bayern Munich.  Won 7 trophies in three years.

**2016-17**
Became the manager of the Manchester City.

**2017-18**
Won the EFL Cup and Premier League, finishing the season with a record-breaking 100 points.

**2018-19**
Began the season with a 2–0 victory over FA Cup holders Chelsea to win the 2018 FA Community Shield.
his side played Chelsea in the EFL Cup Final held at Wembley Stadium. The game ended 0–0 after extra time, but Manchester City won 4–3 on penalties to retain the trophy for the second year in a row. 
Secured a second consecutive Premier League title. His side finished on 98 points, one point above Liverpool.

*PERSONAL LIFE*
-

**1971**
Was born on 18 January 1971 in Santpedor, Barcelona, Catalonia.

**2014**
Met my wife when I was 18. We married on 29 May 2014.
We have three children named Maria, Màrius, and Valentina.
