### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by denys-hryshakin** [denys-hryshakin/homepage#8]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by colloborator-bsa** [comment]
### *FAVOURITE SON OF SANTPEDOR*
Pep Guardiola hails from the small Catalan town of Santpedor in north-east Spain. And the home ground of local team CF Santpedor is now called Camp Municipal Josep Guardiola in honour of Guardiola’s achievements. The municipal council also named Guardiola their “favourite son of the town” in October 2009.

### *CROUCH, THAT HURT!*
Who is Pep’s favourite striker? Messi? Nope. Lewandoski? Nope. Augero? Nope. It’s Peter Crouch. During the 2006 World Cup in Germany, Guardiola wrote a series of columns for El Pais where he gushed over a favourite striker from the tournament, the lanky Crouch. “Wayne Rooney is perhaps more decisive and beautiful to watch,” he wrote, “but what’s certain is that Crouch conditions you more. With Crouch, you have to play to Crouch’s game. And playing to Crouch’s game gives you a lot.”

### *NO AUTOGRAPH FOR PEP*
Guardiola was once refused an autograph by Michel Platini, when offered a poster of the Frenchman, while doing ball-boy duties. Platini’s poster adorned Guardiola’s childhood wall.

### *WHERE FOOTBALL MEETS ART*
Guardiola knows and loves a work of art! After leaving Barcelona, he spent much of his sabbatical in New York around the art galleries of the Big Apple.

### *HIS LOVE SUITS HIM WELL*
Guardiola’s relationship with wife Cristina Serra grew around the latter’s family clothes shop in Manresa, in Spain’s north east. And that’s the secret to his smart dapper looks.  Christine is heiress to the family owned clothing boutique Serra Claret and is responsible for his dressing sense. Ah, he also got featured in the cover of Spanish edition of GQ, the men’s magazine.

### *THE AUTHOR*
‘La meva gent, el meu futbol’ (my people, my football) – Ever heard of this book? Well, it’s authored by Pep along with two respected football journalists from Spain – Lu Martin and Miguel Rico. Released in 2001, the book is so difficult to find that it will cost you thousands of dollars even if you manage you find it. Its only available in Catalan but it’s out of print and Pep doesn’t want it republished.
